version: '3'
services:
  redis:
    image: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    container_name: redis
    volumes:
      - /redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
 
  web:
    build: ./services/web
    command: python app.py
    volumes:
      - ./services/web/:/usr/src/app/
    depends_on:
      - redis
    ports:
      - 5000:5000
    # env_file:
    #   - ./.env.dev


    build: ./
    working_dir: /var/www/app
    ports:
     - "5000:5000"
    volumes:
     - ./:/var/www/app:rw
    depends_on:
     - redis